# Use the official MongoDB image as the base
FROM mongo:6.0

# (Optional) If you want to use custom MongoDB configurations,
# uncomment the lines below and place a mongod.conf in this folder:
# COPY mongod.conf /etc/mongod.conf
# CMD ["mongod", "--config", "/etc/mongod.conf"]

# (Optional) If you want to initialize the database with custom collections, roles, or users,
# you can copy .js or .sh scripts into this directory. 
# MongoDB will execute them in alphabetical order upon first container startup.
# COPY ./init-scripts/ /docker-entrypoint-initdb.d/
